### PR TITLE
added static files caching to improve load times

### PR DESCRIPTION
**Pull request by besque**
This PR addresses issue #439  by implementing static file caching.

Changes made:
- Added datetime library to the list of standard imports
- Added caching headers for all files in static directory
- Set Cache-Control, Expires, Pragma, and Vary headers

Testing done:
- Verified caching works using browser DevTools Network tab
- Confirmed static files show "(from disk cache)" on subsequent loads
- Load times improved for static resources
- Dynamic routes still work as expected

**RESULT :** 

before:
image

after: 
image

### CODE REVIEW

**Comment by niccokunzmann** [comment]
nice. would you be happy to write tests for this? There are already tests that make requests. It would be nice to check that static files get cached but the dynamic ones don't.
How is that for you?

I want to make sure this does not get destroyed in the future.

**Comment by niccokunzmann** [comment]
I have a cache time for the resources like .ics urls that the calendar requests. it would make sense to use that on the dynamic resources, maybe.  What is your idea?

**Comment by besque** [comment]
hey sure, gladly!

 I'm not sure which dynamic resources to add a cache time to, I feel the current behaviour works just fine.
 
 I'll focus on writing tests to verify the current caching behaviour works as intended.

**Comment by niccokunzmann** [comment]
Thanks!

**Pull request merged**
