### PR TITLE
Strange character do not show if .ics in UTF-8 coding

### PR DESCRIPTION
**Pull request by Gomercic**
Events in the calendar are not displayed correctly with strange characters (like šđčćžŠĐČĆŽ). .ics file is encoded in UTF-8.

open calendar2

### CODE REVIEW

**Comment by niccokunzmann** [comment]
Uh. Thanks for discovering this. I wonder: There are a lot of commits in the pull request. Which one is the one that solves the problem?

**Comment by niccokunzmann** [comment]
Do you have an ICS file that can be used to reproduce the problem?

**Comment by Gomercic** [comment]
[Anatomija s organogenezom domaćih životinja II.Ics.txt](https://github.com/niccokunzmann/open-web-calendar/files/10439428/Anatomija.s.organogenezom.domacih.zivotinja.II.Ics.txt)

**Comment by niccokunzmann** [comment]
Thanks! This way, I can look into it!

**Comment by niccokunzmann** [comment]
I will have a look at that!Message ID: 
***@***.***>

**Comment by niccokunzmann** [comment]
See #152. The fix should be deployed tomorrow.

**Pull request closed without merging**
